version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: DataBaseFirstGate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: jdbc:postgresql://localhost:5432/DataBaseFirstGate
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
    depends_on:
      - db