name: Deploy Dockerhub

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Restore Maven Package
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t investorbeejay/my-app:latest .

      - name: Push Docker image to Docker Hub
        run: docker push investorbeejay/my-app:latest

      - name: Deploy to AWS EC2
        env:
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          AWS_HOST: ${{ secrets.AWS_HOST }}
        run: |
          # Write the private key to a file
          echo "${AWS_PRIVATE_KEY}" > private_key.pem
          # Set appropriate permissions for the private key file
          chmod 600 private_key.pem
          
          # SSH into the EC2 instance and run the deployment commands
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${AWS_HOST} << EOF
            # Modify permissions for the Docker socket if necessary
            sudo chmod 666 /var/run/docker.sock
            # Pull the latest Docker image
            docker pull investorbeejay/my-app:latest
            # Stop and remove any existing container
            docker stop my-web-app || true
            docker rm my-web-app || true
            # Run the new container
            docker run -d --name my-web-app -p 8080:8080 investorbeejay/my-app:latest
          EOF
